"""Generate TypeScript types from the export schema.

The dashboard queries Parquet files whose columns are declared in
`chatsbom.export.schema`. Generating the types rather than hand-writing
them means a column rename is a compile error on the TypeScript side, not
an `undefined` three layers into a chart.
"""
from chatsbom.export.schema import ColumnType
from chatsbom.export.schema import ExportColumn
from chatsbom.export.schema import ExportSchema
from chatsbom.export.schema import ExportTable

HEADER = """// Generated by `chatsbom export schema`. Do not edit.
//
// Source of truth: chatsbom/export/schema.py
// Regenerate with: uv run chatsbom export schema --typescript <path>
"""

_TS_TYPES: dict[ColumnType, str] = {
    ColumnType.STRING: 'string',
    ColumnType.INTEGER: 'number',
    ColumnType.DATE: 'string',
    ColumnType.STRING_LIST: 'string[]',
}

# repositories -> RepositoryRow, artifacts -> ArtifactRow
_IRREGULAR = {'repositories': 'Repository', 'artifacts': 'Artifact'}


def _interface_name(table: ExportTable) -> str:
    stem = _IRREGULAR.get(table.name)
    if stem is None:
        stem = ''.join(p.title() for p in table.name.split('_')).rstrip('s')
    return f'{stem}Row'


def _constant_name(table: ExportTable) -> str:
    singular = _IRREGULAR.get(table.name, table.name).upper()
    return f'{singular}_COLUMNS'


def _ts_type(column: ExportColumn) -> str:
    if column.ts_type:
        return column.ts_type
    return _TS_TYPES[column.type]


def _union(values: list[str]) -> str:
    return ' | '.join(f"'{v}'" for v in values)


def render_typescript(schema: ExportSchema) -> str:
    """Render the whole schema as a standalone TypeScript module."""
    parts: list[str] = [HEADER]

    parts.append(f"export const SCHEMA_VERSION = '{schema.version}';\n")

    # Named unions for every enum column, declared once and shared.
    emitted: set[str] = set()
    for table in schema.tables:
        for column in table.columns:
            if not column.enum or not column.ts_type:
                continue
            if column.ts_type in emitted:
                continue
            emitted.add(column.ts_type)
            parts.append(
                f'/** {column.description} */\n'
                f'export type {column.ts_type} = {_union(column.enum)};\n'
                f'export const {column.ts_type.upper()}S: '
                f'readonly {column.ts_type}[] = '
                f'[{", ".join(chr(39) + v + chr(39) for v in column.enum)}];\n',
            )

    for table in schema.tables:
        fields = '\n'.join(
            f'  /** {c.description} */\n  {c.name}: {_ts_type(c)};'
            for c in table.columns
        )
        parts.append(
            f'/** {table.description} */\n'
            f'export interface {_interface_name(table)} {{\n{fields}\n}}\n',
        )

        columns = ', '.join(f"'{name}'" for name in table.column_names)
        parts.append(
            f'export const {_constant_name(table)} = '
            f'[{columns}] as const;\n',
        )

    parts.append(
        '/** Parquet file name per table, relative to the data base URL. */\n'
        'export const DATA_FILES = {\n'
        + ''.join(
            f"  {t.name}: '{t.name}.parquet',\n" for t in schema.tables
        )
        + '} as const;\n',
    )

    return '\n'.join(parts)
