-- The D1 export of the contract fixture, generated by
-- web/test/fixtures/contract/build.py. Do not edit.

-- ==== 01-schema.sql ====
-- ChatSBOM D1 schema. Apply before the data.

DROP TABLE IF EXISTS meta;
DROP TABLE IF EXISTS agg_edges;
DROP TABLE IF EXISTS agg_source_comparison;
DROP TABLE IF EXISTS agg_dependency_buckets;
DROP TABLE IF EXISTS agg_top_packages;
DROP TABLE IF EXISTS agg_ecosystem_coverage;
DROP TABLE IF EXISTS agg_language_coverage;
DROP TABLE IF EXISTS agg_relationship_split;
DROP TABLE IF EXISTS agg_totals;
DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS licenses;
DROP TABLE IF EXISTS kinds;
DROP TABLE IF EXISTS versions;
DROP TABLE IF EXISTS packages;
DROP TABLE IF EXISTS observations;
DROP TABLE IF EXISTS artifacts;
DROP TABLE IF EXISTS repositories;

-- One row per repository of the current search snapshot, collected or not.
CREATE TABLE repositories (
  id INTEGER,
  owner TEXT NOT NULL,
  repo TEXT NOT NULL,
  stars INTEGER NOT NULL,
  language TEXT NOT NULL,
  github_language TEXT NOT NULL,
  language_bucket TEXT NOT NULL,
  ecosystems TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT NOT NULL,
  license_spdx_id TEXT NOT NULL,
  pushed_at TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  sbom_ref TEXT NOT NULL,
  sbom_commit_sha TEXT NOT NULL,
  direct_dependencies INTEGER NOT NULL,
  total_dependencies INTEGER NOT NULL,
  PRIMARY KEY (id)
);

-- One row per observed dependency, as four integers.
CREATE TABLE artifacts (
  repository_id INTEGER NOT NULL,
  package_id INTEGER NOT NULL,
  version_id INTEGER NOT NULL,
  kind_id INTEGER NOT NULL
);

-- When each source last observed each repository: the date of its current observation, per repository and source.
CREATE TABLE observations (
  repository_id INTEGER NOT NULL,
  source TEXT NOT NULL,
  observed_at TEXT NOT NULL
);

-- Distinct package names, referenced by artifacts.
CREATE TABLE packages (
  id INTEGER,
  name TEXT NOT NULL,
  repositories INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

-- Distinct version strings, referenced by artifacts.
CREATE TABLE versions (
  id INTEGER,
  version TEXT NOT NULL,
  PRIMARY KEY (id)
);

-- The 45 observed combinations of the five low-cardinality columns, referenced by artifacts instead of repeated per row.
CREATE TABLE kinds (
  id INTEGER,
  type TEXT NOT NULL,
  found_by TEXT NOT NULL,
  relationship TEXT NOT NULL,
  source TEXT NOT NULL,
  version_kind TEXT NOT NULL,
  PRIMARY KEY (id)
);

-- Licence shares, precomputed.
CREATE TABLE licenses (
  license TEXT NOT NULL,
  repository_count INTEGER NOT NULL,
  package_count INTEGER NOT NULL
);

-- Monthly adoption series per package, per source. Two sources measure differently, so a series that mixed them would show a change of instrument as a change in adoption.
CREATE TABLE history (
  name TEXT NOT NULL,
  month TEXT NOT NULL,
  source TEXT NOT NULL,
  repository_count INTEGER NOT NULL,
  direct_count INTEGER NOT NULL
);

-- The numbers the tiles and the footer show. One row.
CREATE TABLE agg_totals (
  repositories INTEGER NOT NULL,
  dependencies INTEGER NOT NULL,
  packages INTEGER NOT NULL,
  classified INTEGER NOT NULL,
  tracked INTEGER NOT NULL
);

-- Declared / inherited / undetermined, per ecosystem and overall.
CREATE TABLE agg_relationship_split (
  ecosystem TEXT NOT NULL,
  relationship TEXT NOT NULL,
  records INTEGER NOT NULL
);

-- Repositories per GitHub language (top twelve, other, none), and how many each source covers.
CREATE TABLE agg_language_coverage (
  language TEXT NOT NULL,
  repositories INTEGER NOT NULL,
  with_sbom INTEGER NOT NULL,
  with_syft INTEGER NOT NULL,
  with_depgraph INTEGER NOT NULL,
  with_manifest INTEGER NOT NULL
);

-- Per ecosystem: repositories that have it, and how many of those each source covers.
CREATE TABLE agg_ecosystem_coverage (
  ecosystem TEXT NOT NULL,
  repositories INTEGER NOT NULL,
  with_any INTEGER NOT NULL,
  with_syft INTEGER NOT NULL,
  with_depgraph INTEGER NOT NULL,
  with_manifest INTEGER NOT NULL
);

-- The ranking, precomputed per filter combination: the panel has exactly two controls, so the set of answers is finite.
CREATE TABLE agg_top_packages (
  direct_only INTEGER NOT NULL,
  ecosystem TEXT NOT NULL,
  rank INTEGER NOT NULL,
  name TEXT NOT NULL,
  repository_count INTEGER NOT NULL,
  direct_count INTEGER NOT NULL
);

-- Repositories per dependency-count bucket.
CREATE TABLE agg_dependency_buckets (
  bucket TEXT NOT NULL,
  position INTEGER NOT NULL,
  repositories INTEGER NOT NULL
);

-- Dependency records per ecosystem, split by collector.
CREATE TABLE agg_source_comparison (
  ecosystem TEXT NOT NULL,
  syft INTEGER NOT NULL,
  depgraph INTEGER NOT NULL,
  manifest INTEGER NOT NULL
);

-- Package-to-package dependency edges, aggregated by name: how many repositories show this parent pulling in this child.
CREATE TABLE agg_edges (
  parent_id INTEGER NOT NULL,
  child_id INTEGER NOT NULL,
  repositories INTEGER NOT NULL
);

-- Provenance, for the same debugging the Parquet manifest serves: which build produced this and how fresh the rows are. One row.
CREATE TABLE meta (
  generator TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  observed_from TEXT NOT NULL,
  observed_to TEXT NOT NULL
);

-- ==== 02-agg_edges-0001.sql ====
-- ChatSBOM D1 data: agg_edges, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of agg_edges wrote, which are then applied again.
DELETE FROM agg_edges WHERE rowid >= 1;
INSERT INTO agg_edges (parent_id,child_id,repositories) VALUES (1,2,2),(1,4,3),(1,11,3),(1,12,2),(2,1,1),(4,10,4),(5,1,5),(5,4,4),(5,11,3),(5,14,2),(11,15,2),(12,2,2),(14,4,3),(14,10,3);

-- ==== 02-artifacts-0001.sql ====
-- ChatSBOM D1 data: artifacts, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of artifacts wrote, which are then applied again.
DELETE FROM artifacts WHERE rowid >= 1;
INSERT INTO artifacts (repository_id,package_id,version_id,kind_id) VALUES (11,1,1,1),(11,2,2,1),(10,3,3,2),(3,4,4,3),(11,4,5,1),(11,5,6,4),(4,6,7,5),(5,7,8,6),(6,7,9,7),(7,7,10,6),(7,7,9,7),(8,7,11,8),(8,7,12,6),(8,7,13,6),(9,7,14,9),(9,7,15,7),(1,8,16,10),(1,8,17,11),(1,8,18,11),(2,8,16,12),(3,8,16,13),(3,8,16,14),(3,8,16,15),(4,8,19,16),(10,8,20,17),(1,9,21,10),(2,9,21,10),(3,10,22,3),(11,10,23,1),(11,11,24,1),(11,12,25,1),(10,13,26,18),(11,14,27,1),(11,15,28,1);

-- ==== 02-history-0001.sql ====
-- ChatSBOM D1 data: history, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of history wrote, which are then applied again.
DELETE FROM history WHERE rowid >= 1;
INSERT INTO history (name,month,source,repository_count,direct_count) VALUES ('body-parser','2026-02','syft',1,0),('bytes','2026-02','syft',1,0),('certifi','2026-02','syft',1,0),('debug','2026-09','github-depgraph',1,0),('debug','2026-02','syft',1,0),('express','2026-02','syft',1,1),('jakarta.mail','2026-02','manifest',1,1),('laravel/framework','2026-09','github-depgraph',3,3),('laravel/framework','2026-02','syft',3,3),('mail','2026-09','github-depgraph',2,2),('mail','2026-01','syft',1,0),('mail','2026-02','syft',5,3),('mini_mime','2026-02','syft',2,0),('ms','2026-09','github-depgraph',1,0),('ms','2026-02','syft',1,0),('qs','2026-02','syft',1,0),('raw-body','2026-02','syft',1,0),('requests','2026-02','syft',1,1),('send','2026-02','syft',1,0),('side-channel','2026-02','syft',1,0);

-- ==== 02-kinds-0001.sql ====
-- ChatSBOM D1 data: kinds, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of kinds wrote, which are then applied again.
DELETE FROM kinds WHERE rowid >= 1;
INSERT INTO kinds (id,type,found_by,relationship,source,version_kind) VALUES (1,'npm','cataloger','transitive','syft','resolved'),(2,'pypi','cataloger','unknown','syft','resolved'),(3,'npm','github-dependency-graph','transitive','github-depgraph','resolved'),(4,'npm','cataloger','direct','syft','resolved'),(5,'maven','cataloger','direct','manifest','constraint'),(6,'composer','github-dependency-graph','direct','github-depgraph','constraint'),(7,'composer','cataloger','direct','syft','resolved'),(8,'composer','github-dependency-graph','transitive','github-depgraph','unversioned'),(9,'composer','cataloger','transitive','syft','resolved'),(10,'gem','cataloger','transitive','syft','resolved'),(11,'gem','github-dependency-graph','direct','github-depgraph','constraint'),(12,'gem','cataloger','direct','syft','resolved'),(13,'gem','github-dependency-graph','direct','github-depgraph','resolved'),(14,'gem','ruby-gemfile-cataloger','direct','syft','resolved'),(15,'gem','ruby-gemspec-cataloger','direct','syft','resolved'),(16,'maven','cataloger','direct','syft','resolved'),(17,'pypi','cataloger','transitive','syft','resolved'),(18,'pypi','cataloger','direct','syft','resolved');

-- ==== 02-licenses-0001.sql ====
-- ChatSBOM D1 data: licenses, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of licenses wrote, which are then applied again.
DELETE FROM licenses WHERE rowid >= 1;
INSERT INTO licenses (license,repository_count,package_count) VALUES ('',7,5),('MIT',7,11),('Apache-2.0',2,2),('BSD-3-Clause',1,1),('MPL-2.0',1,1);

-- ==== 02-meta-0001.sql ====
-- ChatSBOM D1 data: meta, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of meta wrote, which are then applied again.
DELETE FROM meta WHERE rowid >= 1;
INSERT INTO meta (generator,schema_version,observed_from,observed_to) VALUES ('chatsbom/0.5.4','8','2026-02-11','2026-09-14');

-- ==== 02-observations-0001.sql ====
-- ChatSBOM D1 data: observations, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of observations wrote, which are then applied again.
DELETE FROM observations WHERE rowid >= 1;
INSERT INTO observations (repository_id,source,observed_at) VALUES (1,'github-depgraph','2026-09-13'),(1,'syft','2026-02-01'),(2,'syft','2026-02-11'),(3,'github-depgraph','2026-09-13'),(3,'syft','2026-02-11'),(4,'manifest','2026-02-11'),(4,'syft','2026-02-11'),(5,'github-depgraph','2026-09-13'),(6,'syft','2026-02-11'),(7,'github-depgraph','2026-09-13'),(7,'syft','2026-02-11'),(8,'github-depgraph','2026-09-14'),(9,'syft','2026-02-11'),(10,'syft','2026-02-11'),(11,'syft','2026-02-11');

-- ==== 02-packages-0001.sql ====
-- ChatSBOM D1 data: packages, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of packages wrote, which are then applied again.
DELETE FROM packages WHERE rowid >= 1;
INSERT INTO packages (id,name) VALUES (1,'body-parser'),(2,'bytes'),(3,'certifi'),(4,'debug'),(5,'express'),(6,'jakarta.mail'),(7,'laravel/framework'),(8,'mail'),(9,'mini_mime'),(10,'ms'),(11,'qs'),(12,'raw-body'),(13,'requests'),(14,'send'),(15,'side-channel');

-- ==== 02-repositories-0001.sql ====
-- ChatSBOM D1 data: repositories, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of repositories wrote, which are then applied again.
DELETE FROM repositories WHERE rowid >= 1;
INSERT INTO repositories (id,owner,repo,stars,language,github_language,language_bucket,ecosystems,url,description,license_spdx_id,pushed_at,observed_at,sbom_ref,sbom_commit_sha,direct_dependencies,total_dependencies) VALUES (1,'rails','rails',58000,'ruby','Ruby','ruby','["gem"]','https://github.com/rails/rails','','MIT','2026-02-11','2026-09-13','main','r1',1,2),(2,'mastodon','mastodon',47000,'ruby','Ruby','ruby','["gem"]','https://github.com/mastodon/mastodon','','MIT','2026-02-11','2026-02-11','main','m1',1,2),(3,'discourse','discourse',47000,'ruby','Ruby','ruby','["gem","npm"]','https://github.com/discourse/discourse','','MIT','2026-02-11','2026-09-13','main','d1',1,3),(4,'apache','james',900,'java','Java','java','["maven"]','https://github.com/apache/james','','MIT','2026-02-11','2026-02-11','main','j1',2,2),(5,'laravel','laravel',80000,'php','PHP','php','["composer"]','https://github.com/laravel/laravel','','MIT','2026-02-11','2026-09-13','','',1,1),(6,'monicahq','monica',22000,'php','PHP','php','["composer"]','https://github.com/monicahq/monica','','MIT','2026-02-11','2026-02-11','main','mo1',1,1),(7,'firefly-iii','firefly-iii',16000,'php','PHP','php','["composer"]','https://github.com/firefly-iii/firefly-iii','','MIT','2026-02-11','2026-09-13','main','f1',1,1),(8,'koel','koel',16000,'php','PHP','php','["composer"]','https://github.com/koel/koel','','MIT','2026-02-11','2026-09-14','','',1,1),(9,'akaunting','akaunting',9000,'php','PHP','php','["composer"]','https://github.com/akaunting/akaunting','','MIT','2026-02-11','2026-02-11','main','a1',1,1),(10,'psf','app',500,'python','Python','python','["pypi"]','https://github.com/psf/app','','MIT','2026-02-11','2026-02-11','main','p1',1,3),(11,'expressjs','site',100,'','','none','["npm"]','https://github.com/expressjs/site','','MIT','2026-02-11','2026-02-11','main','e1',1,9),(12,'golang','tools',50,'go','Go','go','[]','https://github.com/golang/tools','','MIT','2026-02-11','2026-02-11','','',0,0);

-- ==== 02-versions-0001.sql ====
-- ChatSBOM D1 data: versions, part 1. Apply after 01-schema.sql and
-- the parts before it. Safe to apply again: it first removes what it and
-- the later parts of versions wrote, which are then applied again.
DELETE FROM versions WHERE rowid >= 1;
INSERT INTO versions (id,version) VALUES (1,'1.20.2'),(2,'3.1.2'),(3,'2024.2.2'),(4,'4.3.4'),(5,'2.6.9'),(6,'4.19.2'),(7,'2.1.0'),(8,'^12.0'),(9,'v12.49.0'),(10,'^11.0|^12.0'),(11,''),(12,'^10.0'),(13,'^9.0'),(14,'v10.48.0'),(15,'v11.2.0'),(16,'2.8.1'),(17,'>= 2.7'),(18,'~> 2.8'),(19,'1.4.7'),(20,'0.0.1'),(21,'1.1.5'),(22,'2.1.2'),(23,'2.0.0'),(24,'6.11.0'),(25,'2.5.2'),(26,'2.32.0'),(27,'0.18.0'),(28,'1.0.4');

-- ==== 03-aggregates.sql ====
-- ChatSBOM D1 aggregates. Apply after the data, 02-*.sql.

-- Safe to apply again: every table this script fills is emptied first,
-- so a second run replaces what the first wrote rather than adding a
-- second copy of it. The UPDATE of `packages` sets the same numbers.
DELETE FROM agg_totals;
DELETE FROM agg_relationship_split;
DELETE FROM agg_language_coverage;
DELETE FROM agg_ecosystem_coverage;
DELETE FROM agg_top_packages;
DELETE FROM agg_dependency_buckets;
DELETE FROM agg_source_comparison;

-- `WHERE total_dependencies > 0`, because the other three numbers
-- here describe the analysed set and this one has to as well.
--
-- The repositories table holds every repository of the current search
-- snapshot, including those with no dependency row, while ClickHouse's
-- `mv_totals` counts the ones that have one. The dashboard reads
-- this field under the label "repositories with dependency data" — a
-- label made true for one backend and false for the other. Two stores
-- answering the same call differently is how a fallback becomes a
-- different dataset. `tracked` is the snapshot, the denominator.
INSERT INTO agg_totals
  (repositories, dependencies, packages, classified, tracked)
SELECT
  (SELECT count(*) FROM repositories WHERE total_dependencies > 0),
  (SELECT count(*) FROM artifacts),
  (SELECT count(*) FROM packages),
  (SELECT count(*) FROM artifacts a JOIN kinds k ON k.id = a.kind_id
   WHERE k.relationship <> 'unknown'),
  (SELECT count(*) FROM repositories);

-- Per ecosystem and, as the '' row, the whole corpus. The overview reads
-- the '' row; the ecosystem filter reads one of the others. Records
-- partition by ecosystem (a record has one type), so the per-ecosystem
-- rows add up to the '' row.
INSERT INTO agg_relationship_split (ecosystem, relationship, records)
SELECT '', k.relationship, count(*)
FROM artifacts a JOIN kinds k ON k.id = a.kind_id
GROUP BY k.relationship;

INSERT INTO agg_relationship_split (ecosystem, relationship, records)
SELECT k.type, k.relationship, count(*)
FROM artifacts a
JOIN kinds k ON k.id = a.kind_id
WHERE k.type <> ''
GROUP BY k.type, k.relationship;

-- Denormalised onto `packages` so the search box can rank by it.
--
-- Ordering the search by popularity is the whole point: alphabetically,
-- `laravel` returns forty `laravel-enso/*` packages with one dependant
-- each ('-' is 0x2D, '/' is 0x2F) and never reaches `laravel/framework`
-- with 98. But computing the count per matching row means a correlated
-- subquery over `artifacts` for every candidate, which is the one thing
-- a keystroke-latency query must not do. Stored once here instead.
-- One grouped pass, joined back. Not a correlated subquery: the index
-- that would make one viable, `idx_artifacts_package_id`, is created by
-- `04-indexes.sql` *after* this script, so the subquery form scans the
-- whole artifacts table once per package. Measured on the real export:
-- 225,400 packages against 16,839,566 rows had not finished in 110
-- seconds and would not have; this form takes 3.2 seconds, which also
-- keeps it inside D1's 30-second statement limit.
--
-- Packages the join finds no rows for keep the column's DEFAULT 0.
UPDATE packages SET repositories = counted.n
FROM (
  SELECT package_id, count(DISTINCT repository_id) AS n
  FROM artifacts GROUP BY package_id
) AS counted
WHERE counted.package_id = packages.id;

-- The denominator is every repository of the snapshot, collected or
-- not, folded by GitHub's language (top twelve, other, none).
INSERT INTO agg_language_coverage
  (language, repositories, with_sbom, with_syft, with_depgraph,
   with_manifest)
SELECT r.language_bucket, count(*),
       count(CASE WHEN r.total_dependencies > 0 THEN 1 END),
       count(CASE WHEN s.syft > 0 THEN 1 END),
       count(CASE WHEN s.depgraph > 0 THEN 1 END),
       count(CASE WHEN s.manifest > 0 THEN 1 END)
FROM repositories r
LEFT JOIN (
  SELECT a.repository_id AS id,
         sum(k.source = 'syft') AS syft,
         sum(k.source = 'github-depgraph') AS depgraph,
         sum(k.source = 'manifest') AS manifest
  FROM artifacts a JOIN kinds k ON k.id = a.kind_id
  GROUP BY a.repository_id
) s ON s.id = r.id
GROUP BY r.language_bucket;

-- A repository counts under every ecosystem it has: its artifacts' or
-- its manifests'. These rows overlap and are not to be summed.
INSERT INTO agg_ecosystem_coverage
  (ecosystem, repositories, with_any, with_syft, with_depgraph,
   with_manifest)
SELECT e.value, count(*),
       count(CASE WHEN s.records > 0 THEN 1 END),
       count(CASE WHEN s.syft > 0 THEN 1 END),
       count(CASE WHEN s.depgraph > 0 THEN 1 END),
       count(CASE WHEN s.manifest > 0 THEN 1 END)
FROM repositories r
JOIN json_each(r.ecosystems) e
LEFT JOIN (
  SELECT a.repository_id AS id,
         k.type AS ecosystem,
         count(*) AS records,
         sum(k.source = 'syft') AS syft,
         sum(k.source = 'github-depgraph') AS depgraph,
         sum(k.source = 'manifest') AS manifest
  FROM artifacts a JOIN kinds k ON k.id = a.kind_id
  GROUP BY a.repository_id, k.type
) s ON s.id = r.id AND s.ecosystem = e.value
GROUP BY e.value;

-- The ranking, per filter combination. The panel has exactly two
-- controls -- declared-only, and ecosystem -- so the answer set is
-- finite and can be enumerated.
--
-- The whole-corpus row counts each name's repositories once. It used
-- to sum the per-language counts, which was exact only while every
-- repository had one language; a repository has as many ecosystems as
-- it has manifests for, and `mail` is a gem and a Maven artifact.
INSERT INTO agg_top_packages
  (direct_only, ecosystem, rank, name, repository_count, direct_count)
WITH counted AS (
  SELECT
    k.type AS ecosystem,
    p.name AS name,
    count(DISTINCT a.repository_id) AS repository_count,
    count(DISTINCT CASE WHEN k.relationship = 'direct'
                        THEN a.repository_id END) AS direct_count
  FROM artifacts a
  JOIN packages p ON p.id = a.package_id
  JOIN kinds k ON k.id = a.kind_id
  GROUP BY k.type, p.name
),
overall AS (
  SELECT
    '' AS ecosystem,
    p.name AS name,
    count(DISTINCT a.repository_id) AS repository_count,
    count(DISTINCT CASE WHEN k.relationship = 'direct'
                        THEN a.repository_id END) AS direct_count
  FROM artifacts a
  JOIN packages p ON p.id = a.package_id
  JOIN kinds k ON k.id = a.kind_id
  GROUP BY p.name
),
unioned AS (
  SELECT * FROM counted WHERE ecosystem <> ''
  UNION ALL SELECT * FROM overall
),
ranked AS (
  SELECT
    direct_only, ecosystem, name, repository_count, direct_count,
    row_number() OVER (
      PARTITION BY direct_only, ecosystem
      ORDER BY CASE WHEN direct_only = 1 THEN direct_count
                    ELSE repository_count END DESC, name ASC
    ) AS rank
  FROM unioned, (SELECT 0 AS direct_only UNION ALL SELECT 1)
)
SELECT direct_only, ecosystem, rank, name, repository_count, direct_count
FROM ranked
WHERE rank <= 30;

INSERT INTO agg_dependency_buckets (bucket, position, repositories)
SELECT bucket, position, count(*) FROM (
  SELECT
    CASE
      WHEN total_dependencies = 0 THEN 'none'
      WHEN total_dependencies < 10 THEN '1-9'
      WHEN total_dependencies < 25 THEN '10-24'
      WHEN total_dependencies < 50 THEN '25-49'
      WHEN total_dependencies < 100 THEN '50-99'
      WHEN total_dependencies < 250 THEN '100-249'
      WHEN total_dependencies < 500 THEN '250-499'
      WHEN total_dependencies < 1000 THEN '500-999'
      ELSE '1000+'
    END AS bucket,
    CASE
      WHEN total_dependencies = 0 THEN 0
      WHEN total_dependencies < 10 THEN 1
      WHEN total_dependencies < 25 THEN 2
      WHEN total_dependencies < 50 THEN 3
      WHEN total_dependencies < 100 THEN 4
      WHEN total_dependencies < 250 THEN 5
      WHEN total_dependencies < 500 THEN 6
      WHEN total_dependencies < 1000 THEN 7
      ELSE 8
    END AS position
  FROM repositories
) GROUP BY bucket, position;

INSERT INTO agg_source_comparison (ecosystem, syft, depgraph, manifest)
SELECT k.type,
       sum(CASE WHEN k.source = 'syft' THEN 1 ELSE 0 END),
       sum(CASE WHEN k.source = 'github-depgraph' THEN 1 ELSE 0 END),
       sum(CASE WHEN k.source = 'manifest' THEN 1 ELSE 0 END)
FROM artifacts a
JOIN kinds k ON k.id = a.kind_id
WHERE k.type <> ''
GROUP BY k.type;

-- ==== 04-indexes.sql ====
-- ChatSBOM D1 indexes. Apply after the data.

CREATE INDEX IF NOT EXISTS idx_artifacts_package_id ON artifacts(package_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_repository_id ON artifacts(repository_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_observations_repository_id_source ON observations(repository_id, source);
CREATE UNIQUE INDEX IF NOT EXISTS idx_packages_name ON packages(name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_versions_version ON versions(version);
CREATE INDEX IF NOT EXISTS idx_repositories_language_bucket ON repositories(language_bucket);
CREATE INDEX IF NOT EXISTS idx_history_name ON history(name);
CREATE INDEX IF NOT EXISTS idx_agg_top_packages_direct_only_ecosystem_rank ON agg_top_packages(direct_only, ecosystem, rank);
CREATE INDEX IF NOT EXISTS idx_agg_relationship_split_ecosystem ON agg_relationship_split(ecosystem);
CREATE INDEX IF NOT EXISTS idx_agg_edges_parent_id ON agg_edges(parent_id);
CREATE INDEX IF NOT EXISTS idx_agg_edges_child_id ON agg_edges(child_id);
