// Generated by `chatsbom export schema`. Do not edit.
//
// Source of truth: chatsbom/export/schema.py
// Regenerate with: uv run chatsbom export schema --typescript <path>

export const SCHEMA_VERSION = '5';

/** Whether the repository declares this package itself, inherited it, or could not be determined. */
export type Relationship = 'direct' | 'transitive' | 'unknown';
export const RELATIONSHIPS: readonly Relationship[] = ['direct', 'transitive', 'unknown'];

/** Which collector produced the row: syft (lockfile, resolved closure) or github-depgraph (manifest, declared only). */
export type ArtifactSource = 'syft' | 'github-depgraph';
export const ARTIFACTSOURCES: readonly ArtifactSource[] = ['syft', 'github-depgraph'];

/** Whether the version is exact, a manifest constraint, or absent. */
export type VersionKind = 'resolved' | 'constraint' | 'unversioned';
export const VERSIONKINDS: readonly VersionKind[] = ['resolved', 'constraint', 'unversioned'];

/** One row per analysed repository. */
export interface RepositoryRow {
  /** GitHub repository id. */
  id: number;
  /** Repository owner login. */
  owner: string;
  /** Repository name. */
  repo: string;
  /** Star count at collection time. */
  stars: number;
  /** Primary language, lowercased. */
  language: string;
  /** Repository URL. */
  url: string;
  /** Repository description. */
  description: string;
  /** SPDX licence id, or empty. */
  license_spdx_id: string;
  /** Last push upstream, as YYYY-MM-DD. */
  pushed_at: string;
  /** When this repository was last scanned, as YYYY-MM-DD. */
  observed_at: string;
  /** Tag or branch the SBOM was taken from. */
  sbom_ref: string;
  /** Full commit SHA the SBOM describes. */
  sbom_commit_sha: string;
  /** Distinct packages the manifest declares. */
  direct_dependencies: number;
  /** Distinct packages in the resolved closure. */
  total_dependencies: number;
  /** Manifest files that were read, relative to the repo root. */
  manifest_sources: string[];
}

export const REPOSITORY_COLUMNS = ['id', 'owner', 'repo', 'stars', 'language', 'url', 'description', 'license_spdx_id', 'pushed_at', 'observed_at', 'sbom_ref', 'sbom_commit_sha', 'direct_dependencies', 'total_dependencies', 'manifest_sources'] as const;

/** One row per (repository, package, version) in the SBOM. */
export interface ArtifactRow {
  /** Joins to repositories.id. */
  repository_id: number;
  /** Package name as the ecosystem spells it. */
  name: string;
  /** Resolved version, or empty. */
  version: string;
  /** Package ecosystem, e.g. gem, npm, go-module. */
  type: string;
  /** Detector that reported the package. */
  found_by: string;
  /** Whether the repository declares this package itself, inherited it, or could not be determined. */
  relationship: Relationship;
  /** Which collector produced the row: syft (lockfile, resolved closure) or github-depgraph (manifest, declared only). */
  source: ArtifactSource;
  /** Whether the version is exact, a manifest constraint, or absent. */
  version_kind: VersionKind;
}

export const ARTIFACT_COLUMNS = ['repository_id', 'name', 'version', 'type', 'found_by', 'relationship', 'source', 'version_kind'] as const;

/** Package counts per SPDX licence, by ecosystem. */
export interface LicenseRow {
  /** SPDX expression, or empty when unknown. */
  license: string;
  /** Package ecosystem. */
  type: string;
  /** Distinct packages under this licence. */
  package_count: number;
  /** Repositories carrying one. */
  repository_count: number;
}

export const LICENSES_COLUMNS = ['license', 'type', 'package_count', 'repository_count'] as const;

/** Monthly adoption per package: how many repositories used it, and how many declared it. The temporal series a snapshot cannot give. */
export interface HistoryRow {
  /** Package name. */
  name: string;
  /** Observation month, YYYY-MM. */
  month: string;
  /** Repositories using it that month. */
  repository_count: number;
  /** Of those, how many declared it. */
  direct_count: number;
}

export const HISTORY_COLUMNS = ['name', 'month', 'repository_count', 'direct_count'] as const;

/** Parquet file name per table, relative to the data base URL. */
export const DATA_FILES = {
  repositories: 'repositories.parquet',
  artifacts: 'artifacts.parquet',
  licenses: 'licenses.parquet',
  history: 'history.parquet',
} as const;
